- hosts: all
  become: true
  vars_files:
    - vars.yaml
    - dest.yaml

  roles: 
    - test-connectivity
    - update-packages
    - cloning-repo-yolo
    - docker-engine
    - install-docker
    - start-docker
    - install-python
    - mongodb-database
    - yolo-backend
    - yolo-frontend
